spring:
  application:
    name: stock-management
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: configserver:http://backendproxy:8341/configuration
  cloud:
    config:
      username: root
      password: ${SPRING_CLOUD_CONFIG_PASSWORD}

  datasource:
    url: jdbc:postgresql://postgres-db:5432/stockdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # La propriété 'database-platform' est la manière moderne de définir le dialecte
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Très utile pour voir les requêtes SQL générées